print("Ejemplo mates variables")
print("Introduzca el número 1")
numero1 = input()
print("Introduzca número 2")
numero2 = input ()
suma = "numero1" +  numero2
print("suma:", suma)
print("resta", resta)
print(str(numero1) + "*" + str(numero2) + "=" + str(multiplicacion))
print("division" , division)
print("suma:", suma)
redondeo = int(division)
print("redondeo division", redondeo)